name: publish

on: [push, workflow_dispatch]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/Lunaar-SMP/python3.11-zulu17:latest