name: publish
on: [push]
jobs:
publish-zulu-python3.11:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the zulu-python3.11 Docker image
run: |
       docker build . --tag ghcr.io/Lunaar-SMP/zulu-python3.11:latest
       docker run ghcr.io/Lunaar-SMP/zulu-python3.11:latest
       docker push ghcr.io/Lunaar-SMP/zulu-python3.11:latest